const data = {
  products: [
    {
      name: 'Mustang Shelby',
      category: 'Cars',
      image: '/images/car1.jpg',
      price: 4000,
      countInStock: 10,
      brand: 'Mustang',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Yamaha Power Bike',
      category: 'Bikes',
      image: '/images/bike2.png',
      price: 6000,
      countInStock: 0,
      brand: 'Yamaha',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Tesla v16',
      category: 'Cars',
      image: '/images/car2.jpg',
      price: 22000,
      countInStock: 1,
      brand: 'Tesla',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Aventador',
      category: 'Cars',
      image: '/images/car3.png',
      price: 8000,
      countInStock: 15,
      brand: 'Lamborghini',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Alienware G6',
      category: 'Cars',
      image: '/images/car4.jpg',
      price: 65000,
      countInStock: 5,
      brand: 'Bugatti',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Avaron v18',
      category: 'Bikes',
      image: '/images/bike3.jpg',
      price: 13500,
      countInStock: 12,
      brand: 'Yamaha',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Matrix v15',
      category: 'Bikes',
      image: '/images/bike1.jpg',
      price: 10000,
      countInStock: 12,
      brand: 'Bugatti',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Range Rover',
      category: 'Cars',
      image: '/images/car5.png',
      price: 1500,
      countInStock: 12,
      brand: 'Toyota',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Crustor',
      category: 'Pants',
      image: '/images/car6.jpg',
      price: 1500,
      countInStock: 12,
      brand: 'Toyota',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};


export default data;